		CREATE DATABASE [to_do]  (EDITION = 'GeneralPurpose', SERVICE_OBJECTIVE = 'GP_S_Gen5_1', MAXSIZE = 32 GB) WITH CATALOG_COLLATION = SQL_Latin1_General_CP1_CI_AS;
		GO
		ALTER DATABASE [to_do] SET ANSI_NULL_DEFAULT OFF 
		GO
		ALTER DATABASE [to_do] SET ANSI_NULLS OFF 
		GO
		ALTER DATABASE [to_do] SET ANSI_PADDING OFF 
		GO
		ALTER DATABASE [to_do] SET ANSI_WARNINGS OFF 
		GO
		ALTER DATABASE [to_do] SET ARITHABORT OFF 
		GO
		ALTER DATABASE [to_do] SET AUTO_SHRINK OFF 
		GO
		ALTER DATABASE [to_do] SET AUTO_UPDATE_STATISTICS ON 
		GO
		ALTER DATABASE [to_do] SET CURSOR_CLOSE_ON_COMMIT OFF 
		GO
		ALTER DATABASE [to_do] SET CONCAT_NULL_YIELDS_NULL OFF 
		GO
		ALTER DATABASE [to_do] SET NUMERIC_ROUNDABORT OFF 
		GO
		ALTER DATABASE [to_do] SET QUOTED_IDENTIFIER OFF 
		GO
		ALTER DATABASE [to_do] SET RECURSIVE_TRIGGERS OFF 
		GO
		ALTER DATABASE [to_do] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
		GO
		ALTER DATABASE [to_do] SET ALLOW_SNAPSHOT_ISOLATION ON 
		GO
		ALTER DATABASE [to_do] SET PARAMETERIZATION SIMPLE 
		GO
		ALTER DATABASE [to_do] SET READ_COMMITTED_SNAPSHOT ON 
		GO
		ALTER DATABASE [to_do] SET  MULTI_USER 
		GO
		ALTER DATABASE [to_do] SET ENCRYPTION ON
		GO
		ALTER DATABASE [to_do] SET QUERY_STORE = ON
		GO
		ALTER DATABASE [to_do] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 100, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
		GO
		ALTER DATABASE [to_do] SET  READ_WRITE 
		GO


        CREATE LOGIN dbuser WITH password='#S3cr3t!';
        GO
		CREATE USER dbuser FROM LOGIN dbuser;
		GO

				--- new connection

        use [to_do]
		GO

		CREATE USER dbuser FROM LOGIN dbuser;
		GO
        EXEC sp_addrolemember 'db_datareader', 'dbuser'; 
		EXEC sp_addrolemember 'db_datawriter', 'dbuser';